# Generated by Django 3.2.7 on 2021-10-02 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank_app', '0003_auto_20211001_0752'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='rank',
            field=models.CharField(blank='B', choices=[('G', 'Gold'), ('S', 'Silver'), ('B', 'Basic')], max_length=1),
        ),
    ]
